### ISSUE TITLE
Wrong furigana for some words

### ISSUE THREAD

**Issue by larvata** [passaglia/yomikata#1]
It might be an upstream bug, I'm not sure if it's appropriate to open the ticket here.

Words that contain kanji, end with kana, and where the ending kana is same as the last kana of the preceding kanji.  
e.g.:
```
可愛い (かわいい) 
憎く (にくく)
低く (ひくく)
```

`Dictionary.furigana` function returns the wrong result:

```python
from yomikata.dictionary import Dictionary

dictreader = Dictionary()
print(dictreader.furigana('可愛い'))

# it returns {可愛/かわ}い
# but the correct result should be {可愛/かわい}い

```

**Comment by passaglia** [comment]
This is a big issue, thanks for letting me know. I'm looking into it now.

**Comment by passaglia** [comment]
The bug is in the speach library's from_furi function (https://github.com/neocl/speach/blob/main/speach/ttlig.py), which fails on this class of words. I'll open an issue there, but in the meantime I've pushed a quick-but-ugly solution to fix this in yomikata. @larvata thanks so much for pointing this out!
